routes/web.php
<?php

use App\Http\Controllers\SMS_MessageController;
use App\Http\Controllers\SuperController;
use App\Http\Controllers\SuperHeroController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/login', function () {
    return view('auth.login');
})->name('login');

Route::post('/login', [SuperHeroController::class, 'login']);

Route::group(['middleware' => 'auth'], function () {
    Route::get('/', [SuperController::class, 'index'])->name('home');
    Route::get('/users', [SuperController::class, 'getUsers'])->name('users');
    Route::get('/users/{id}', [SuperController::class, 'getUser'])->name('user');
    Route::get('/businesses', [SuperController::class, 'getBusinesses'])->name('businesses');
    Route::get('/shops', [SuperController::class, 'getShops'])->name('shops');
    Route::get('/managers', [SuperController::class, 'getManagers'])->name('managers');
    Route::get('/items', [SuperController::class, 'getItems'])->name('items');
    Route::get('/shop-items', [SuperController::class, 'getShopItems'])->name('shopItems');
    Route::get('/shop-services', [SuperController::class, 'getShopServices'])->name('shopServices');
    Route::resource('/admins', SuperHeroController::class);
    Route::post('send_sms', [SuperController::class, 'send_sms'])->name('send_sms');

    Route::resource('/messages', SMS_MessageController::class);


    Route::get('/bulk_messages', [SMS_MessageController::class, 'bulk_messages']);
    Route::post('/send_bulk_sms', [SMS_MessageController::class, 'send_bulk_sms'])->name('send_bulk_sms');
});

resources/views/partials/footer.blade.php
<!-- Footer Start -->
<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <script>
                    document.write(new Date().getFullYear())
                </script> &copy; Lonux Admin
            </div>
        </div>
    </div>
</footer>
<!-- end Footer -->

resources/views/partials/head-css.blade.php
<!-- App css -->
<link href="{{ asset('new_look/assets/css/bootstrap.min.css') }}" rel="stylesheet" type="text/css"
    id="bs-default-stylesheet" />
<link href="{{ asset('new_look/assets/css/app.min.css') }}" rel="stylesheet" type="text/css"
    id="app-default-stylesheet" />

<link href="{{ asset('new_look/assets/css/bootstrap-dark.min.css') }}" rel="stylesheet" type="text/css"
    id="bs-dark-stylesheet" />
<link href="{{ asset('new_look/assets/css/app-dark.min.css') }}" rel="stylesheet" type="text/css"
    id="app-dark-stylesheet" />

<!-- icons -->
<link href="{{ asset('new_look/assets/css/icons.min.css') }}" rel="stylesheet" type="text/css" />

resources/views/partials/left-sidebar.blade.php
<!-- ========== Left Sidebar Start ========== -->
<div class="left-side-menu">

    <!-- LOGO -->
    <div class="logo-box">
        <a href="{{ route('home') }}" class="logo logo-dark text-center">
            <span class="logo-sm">
                <img src="{{ asset('new_look/assets/images/lonux-logo-300.png') }}" alt="" height="24">
                <!-- <span class="logo-lg-text-light">Highdmin</span> -->
            </span>
            <span class="logo-lg">
                <img src="{{ asset('new_look/assets/images/lonux-logo-300.png') }}" alt="" height="42">
                <!-- <span class="logo-lg-text-light">H</span> -->
            </span>
        </a>

        <a href="{{ route('home') }}" class="logo logo-light text-center">
            <span class="logo-sm">
                <img src="{{ asset('new_look/assets/images/lonux-logo-300.png') }}" alt="" height="24">
            </span>
            <span class="logo-lg">
                <img src="{{ asset('new_look/assets/images/lonux-logo-300.png') }}" alt="" height="22">
            </span>
        </a>
    </div>

    <div class="h-100" data-simplebar>

        <!-- User box -->
        <div class="user-box text-center">
            <img src="{{ asset('new_look/assets/images/users/user.png') }}" alt="user-img" title="Mat Helme"
                class="rounded-circle avatar-md">
            <div class="dropdown">
                <a href="javascript: void(0);" class="text-dark dropdown-toggle h5 mt-2 mb-1 d-block"
                    data-toggle="dropdown">{{ Auth::user()->name }}</a>
                <div class="dropdown-menu user-pro-dropdown">

                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item">
                        <i class="fe-user mr-1"></i>
                        <span>My Account</span>
                    </a>

                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item">
                        <i class="fe-settings mr-1"></i>
                        <span>Settings</span>
                    </a>

                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item">
                        <i class="fe-lock mr-1"></i>
                        <span>Lock Screen</span>
                    </a>

                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item">
                        <i class="fe-log-out mr-1"></i>
                        <span>Logout</span>
                    </a>

                </div>
            </div>
            <p class="text-muted">{{ Auth::user()->phone }}</p>
        </div>

        <!--- Sidemenu -->
        <div id="sidebar-menu">

            <ul id="side-menu">

                <li class="menu-title">Navigation</li>

                <li>
                    <a href="{{ route('home') }}">
                        <i class="fe-home"></i>
                        <span> Overview </span>
                    </a>
                </li>
                <li>
                    <a href="{{ route('users') }}">
                        <i class="fe-user"></i>
                        <span> Users </span>
                    </a>
                </li>
                <li>
                    <a href="{{ route('businesses') }}">
                        <i class="fas fa-business-time"></i>
                        <span> Businesses </span>
                    </a>
                </li>
                <li>
                    <a href="{{ route('shops') }}">
                        <i class="fas fa-shopping-basket"></i>
                        <span> Shops </span>
                    </a>
                </li>
                <li>
                    <a href="{{ route('managers') }}">
                        <i class="fas fa-wrench"></i>
                        <span> Shop Managers </span>
                    </a>
                </li>
                <li>
                    <a href="{{ route('items') }}">
                        <i class="fas fa-list"></i>
                        <span> Inventory Items </span>
                    </a>
                </li>
                <li>
                    <a href="{{ route('shopItems') }}">
                        <i class="fas fa-shopping-cart"></i>
                        <span> Shop Items </span>
                    </a>
                </li>

                <li>
                    <a href="{{ route('shopServices') }}">
                        <i class="fab fa-shopware"></i>
                        <span> Shop Services </span>
                    </a>
                </li>

                <li>
                    <a href="{{ route('admins.index') }}">
                        <i class="fas fa-user-cog"></i>
                        <span> Super Heroes </span>
                    </a>
                </li>
            </ul>

            <ul id="side-menu">

                <li class="menu-title">SMS Management</li>

                <li>
                    <a href="{{ route('messages.index') }}">
                        <i class="fe-user"></i>
                        <span> Messages </span>
                    </a>
                </li>

                <li>
                    <a href="/bulk_messages">
                        <i class="fe-user"></i>
                        <span> Send Bulk </span>
                    </a>
                </li>
            </ul>

        </div>
        <!-- End Sidebar -->

        <div class="clearfix"></div>

    </div>
    <!-- Sidebar -left -->

</div>
<!-- Left Sidebar End -->

resources/views/partials/title-meta.blade.php
<meta charset="utf-8" />
<title>Lonux {{ $title }}</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description" />
<meta content="Coderthemes" name="author" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<!-- App favicon -->
<link rel="shortcut icon" href="{{ asset('new_look/assets/images/favicon.ico') }}">

resources/views/partials/topbar.blade.php
<!-- Topbar Start -->
<div class="navbar-custom">
    <div class="container-fluid">

        <ul class="list-unstyled topnav-menu float-right mb-0">

            <li class="d-none d-lg-block">
                <form class="app-search">
                    <div class="app-search-box">
                        <div class="input-group">
                            <input type="search" class="form-control" placeholder="Search..." id="top-search">
                            <div class="input-group-append">
                                <button class="btn" type="submit">
                                    <i class="fe-search"></i>
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
            </li>

            <li class="dropdown d-inline-block d-lg-none">
                <a class="nav-link dropdown-toggle arrow-none waves-effect waves-light" data-toggle="dropdown" href="#"
                    role="button" aria-haspopup="false" aria-expanded="false">
                    <i class="fe-search noti-icon"></i>
                </a>
                <div class="dropdown-menu dropdown-lg dropdown-menu-right p-0">
                    <form class="p-3">
                        <input type="text" class="form-control" placeholder="Search ..."
                            aria-label="Recipient's username">
                    </form>
                </div>
            </li>



            <li class="dropdown notification-list topbar-dropdown">
                <a class="nav-link dropdown-toggle waves-effect waves-light" data-toggle="dropdown" href="#"
                    role="button" aria-haspopup="false" aria-expanded="false">
                    <i class="fe-bell noti-icon"></i>
                    <span class="badge badge-danger rounded-circle noti-icon-badge">4</span>
                </a>
                <div class="dropdown-menu dropdown-menu-right dropdown-lg">

                    <!-- item-->
                    <div class="dropdown-item noti-title">
                        <h5 class="m-0">
                            <span class="float-right">
                                <a href="" class="text-dark">
                                    <small>Clear All</small>
                                </a>
                            </span>Notification
                        </h5>
                    </div>

                    <div class="noti-scroll" data-simplebar>

                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item notify-item active">
                            <div class="notify-icon bg-success">
                                <i class="mdi mdi-comment-account-outline"></i>
                            </div>
                            <p class="notify-details">Doug Dukes commented on Admin Dashboard
                                <small class="text-muted">1 min ago</small>
                            </p>
                        </a>

                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item notify-item">
                            <div class="notify-icon">
                                <img src="{{ asset('new_look/assets/images/users/avatar-2.jpg') }}"
                                    class="img-fluid rounded-circle" alt="" />
                            </div>
                            <p class="notify-details">Mario Drummond</p>
                            <p class="text-muted mb-0 user-msg">
                                <small>Hi, How are you? What about our next meeting</small>
                            </p>
                        </a>

                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item notify-item">
                            <div class="notify-icon">
                                <img src="{{ asset('new_look/assets/images/users/user.png') }}"
                                    class="img-fluid rounded-circle" alt="" />
                            </div>
                            <p class="notify-details">Karen Robinson</p>
                            <p class="text-muted mb-0 user-msg">
                                <small>Wow ! this admin looks good and awesome design</small>
                            </p>
                        </a>

                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item notify-item">
                            <div class="notify-icon bg-warning">
                                <i class="mdi mdi-account-plus"></i>
                            </div>
                            <p class="notify-details">New user registered.
                                <small class="text-muted">5 hours ago</small>
                            </p>
                        </a>

                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item notify-item">
                            <div class="notify-icon bg-info">
                                <i class="mdi mdi-comment-account-outline"></i>
                            </div>
                            <p class="notify-details">Caleb Flakelar commented on Admin
                                <small class="text-muted">4 days ago</small>
                            </p>
                        </a>

                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item notify-item">
                            <div class="notify-icon bg-secondary">
                                <i class="mdi mdi-heart"></i>
                            </div>
                            <p class="notify-details">Carlos Crouch liked
                                <b>Admin</b>
                                <small class="text-muted">13 days ago</small>
                            </p>
                        </a>
                    </div>

                    <!-- All-->
                    <a href="javascript:void(0);" class="dropdown-item text-center text-primary notify-item notify-all">
                        View all
                        <i class="fe-arrow-right"></i>
                    </a>

                </div>
            </li>

            <li class="dropdown notification-list topbar-dropdown">
                <a class="nav-link dropdown-toggle nav-user mr-0 waves-effect waves-light" data-toggle="dropdown"
                    href="#" role="button" aria-haspopup="false" aria-expanded="false">
                    <img src="{{ asset('new_look/assets/images/users/user.png') }}" alt="user-image"
                        class="rounded-circle">
                    <span class="pro-user-name ml-1">
                        Maxine K <i class="mdi mdi-chevron-down"></i>
                    </span>
                </a>
                <div class="dropdown-menu dropdown-menu-right profile-dropdown ">
                    <!-- item-->
                    <div class="dropdown-header noti-title">
                        <h6 class="text-overflow m-0">Welcome !</h6>
                    </div>

                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item">
                        <i class="fe-user"></i>
                        <span>My Account</span>
                    </a>

                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item">
                        <i class="fe-settings"></i>
                        <span>Settings</span>
                    </a>

                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item">
                        <i class="fe-help-circle"></i>
                        <span>My Wallet <span class="badge badge-success float-right">3</span> </span>
                    </a>

                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item">
                        <i class="fe-lock"></i>
                        <span>Lock Screen</span>
                    </a>

                    <div class="dropdown-divider"></div>

                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item">
                        <i class="fe-log-out"></i>
                        <span>Logout</span>
                    </a>

                </div>
            </li>

            <li class="dropdown notification-list">
                <a href="javascript:void(0);" class="nav-link right-bar-toggle waves-effect waves-light">
                    <i class="fe-settings noti-icon"></i>
                </a>
            </li>

        </ul>

        <!-- LOGO -->
        <div class="logo-box">
            <a href="index.html" class="logo logo-dark text-center">
                <span class="logo-sm">
                    <img src="{{ asset('new_look/assets/images/lonux-logo-300.png') }}" alt="" height="24">
                    <!-- <span class="logo-lg-text-light">Highdmin</span> -->
                </span>
                <span class="logo-lg">
                    <img src="{{ asset('new_look/assets/images/lonux-logo-300.png') }}" alt="" height="22">
                    <!-- <span class="logo-lg-text-light">H</span> -->
                </span>
            </a>

            <a href="index.html" class="logo logo-light text-center">
                <span class="logo-sm">
                    <img src="{{ asset('new_look/assets/images/lonux-logo-300.png') }}" alt="" height="24">
                </span>
                <span class="logo-lg">
                    <img src="{{ asset('new_look/assets/images/lonux-logo-300.png') }}" alt="" height="22">
                </span>
            </a>
        </div>

        <ul class="list-unstyled topnav-menu topnav-menu-left m-0">
            <li>
                <button class="button-menu-mobile waves-effect waves-light">
                    <i class="fe-menu"></i>
                </button>
            </li>

            <li>
                <!-- Mobile menu toggle (Horizontal Layout)-->
                <a class="navbar-toggle nav-link" data-toggle="collapse" data-target="#topnav-menu-content">
                    <div class="lines">
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>
                </a>
                <!-- End mobile menu toggle-->
            </li>

            <li>
                <div class="page-title-box">
                    <h4 class="page-title">{{ $title }}</h4>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">{{ $subtitle }}</a></li>
                        <li class="breadcrumb-item"><a href="#">{{ $item }}</a></li>
                        <li class="breadcrumb-item active">{{ $activeitem }}</li>
                    </ol>
                </div>
            </li>

        </ul>
        <div class="clearfix"></div>
    </div>
</div>
<!-- end Topbar -->