routes/web.php
<?php

use App\Http\Controllers\SMS_MessageController;
use App\Http\Controllers\SuperController;
use App\Http\Controllers\SuperHeroController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/login', function () {
    return view('auth.login');
})->name('login');

Route::post('/login', [SuperHeroController::class, 'login']);

Route::group(['middleware' => 'auth'], function () {
    Route::get('/', [SuperController::class, 'index'])->name('home');
    Route::get('/users', [SuperController::class, 'getUsers'])->name('users');
    Route::get('/users/{id}', [SuperController::class, 'getUser'])->name('user');
    Route::get('/businesses', [SuperController::class, 'getBusinesses'])->name('businesses');
    Route::get('/shops', [SuperController::class, 'getShops'])->name('shops');
    Route::get('/managers', [SuperController::class, 'getManagers'])->name('managers');
    Route::get('/items', [SuperController::class, 'getItems'])->name('items');
    Route::get('/shop-items', [SuperController::class, 'getShopItems'])->name('shopItems');
    Route::get('/shop-services', [SuperController::class, 'getShopServices'])->name('shopServices');
    Route::resource('/admins', SuperHeroController::class);
    Route::post('send_sms', [SuperController::class, 'send_sms'])->name('send_sms');

    Route::resource('/messages', SMS_MessageController::class);


    Route::get('/bulk_messages', [SMS_MessageController::class, 'bulk_messages']);
    Route::post('/send_bulk_sms', [SMS_MessageController::class, 'send_bulk_sms'])->name('send_bulk_sms');
});

resources/views/messages/bulk.blade.php
@extends('layouts.app')

@section('title')
    @include("partials.title-meta", ["title" => "Send Bulk Messages" ])
@endsection

@section('topbar')
    @include('partials.topbar', ["title" => "Lonux","subtitle" => "Lists", "item" => "Messages",
    "activeitem" => "Bulk"])
@endsection


@section('content')
    <div class="row">
        <div class="col-md-12 text-right">
            <a href="{{route('messages.create')}}" class="btn btn-primary mb-2">Create New Message</a>
        </div>

         @if (Session::has('success'))
            <div class="alert alert-success">{{session('success')}}</div>
        @endif
        @if (Session::has('error'))
            <div class="alert alert-danger">{{session('error')}}</div>
        @endif

        <form method="post" action="{{route('send_bulk_sms')}}" class="row justify-content-center">
            @csrf
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        <h4>Choose Message</h4>
                        <select name="sms_select" class="form-control mb-3">
                        @foreach ($messages as $message)
                            <option value="{{$message->id}}">{{$message->title}}</option>
                        @endforeach
                    </select>
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        <h4>Choose Recipients</h4>
                        <select name="sms_recipients" class="form-control mb-3">
                            <option value="all_business_users">All business users</option>
                            <option value="business_without_shops">Businesses without shops</option>
                            <option value="shops_without_managers">Shops without managers </option>
                            <option value="shop_managers">Shop managers</option>
                            {{-- <option value="customers">Customers</option> --}}
                            {{-- <option value="dispatch_riders">Dispatch Riders</option> --}}
                    </select>
                    </div>
                </div>
            </div>

            <div class="col-12 text-center">
                <button type="submit" class="btn btn-warning">Send Bulk SMS</button>
            </div>
        </form>
        
    </div>
    <!-- end row-->
@endsection

@section('scripts')
@endsection

resources/views/messages/create.blade.php
@extends('layouts.app')

@section('title')
    @include("partials.title-meta", ["title" => "Create New Message" ])
@endsection

@section('topbar')
    @include('partials.topbar', ["title" => "Lonux","subtitle" => "Lists", "item" => "Messages",
    "activeitem" => "Create Message"])
@endsection


@section('content')
    <div class="row">
        <div class="col-12 text-right">
            <a href="{{route('messages.index')}}" class="btn btn-primary mb-2">View Messages</a>
        </div>
        <div class="card col-8">
            <div class="card-body">
                <h4 class="header-title mb-3 text-center">Create a new SMS message</h4>
                <form class="form" method="post" action="{{route('messages.store')}}">
                    @csrf
                    <div class="form-group">
                        <label>SMS Title</label>
                        <input name="title" type="text" class="form-control" placeholder="welcome message" required />
                    </div>
                    <div class="form-group">
                        <label>SMS Body</label>
                        <textarea name="message" maxlength="160" type="text" class="form-control" required></textarea>
                    </div>
                    @if ($errors->any())
                        @foreach ($errors->all() as $error)
                            <div class="alert alert-danger">{{$error}}</div>
                        @endforeach
                    @endif
                    @if (Session::has('success'))
                        <div class="alert alert-success">{{session('success')}}</div>
                    @endif
                    <div class="form-group">
                        <button class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- end row-->
@endsection

@section('scripts')
@endsection

resources/views/messages/edit.blade.php
@extends('layouts.app')

@section('title')
    @include("partials.title-meta", ["title" => "Edit Message" ])
@endsection

@section('topbar')
    @include('partials.topbar', ["title" => "Lonux","subtitle" => "Lists", "item" => "Messages",
    "activeitem" => "Edit Message"])
@endsection


@section('content')
    <div class="row">
    <div class="col-12 text-right">
        <a href="{{route('messages.index')}}" class="btn btn-primary mb-2">View Messages</a>
    </div>
        <div class="card col-8">
            <div class="card-body">
                <h4 class="header-title mb-3 text-center">Create a new SMS message</h4>
                <form class="form" method="post" action="{{route('messages.update', $message->id)}}">
                    @csrf
                    @method('put')
                    <div class="form-group">
                        <label>SMS Title</label>
                        <input name="title" type="text" class="form-control" value="{{$message->title}}" disabled />
                    </div>
                    <div class="form-group">
                        <label>SMS Body</label>
                        <textarea name="message" maxlength="160" type="text" class="form-control" required>{{$message->message}}</textarea>
                    </div>
                    @if ($errors->any())
                        @foreach ($errors->all() as $error)
                            <div class="alert alert-danger">{{$error}}</div>
                        @endforeach
                    @endif
                    @if (Session::has('success'))
                        <div class="alert alert-success">{{session('success')}}</div>
                    @endif
                    <div class="form-group">
                        <button class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- end row-->
@endsection

@section('scripts')
@endsection

resources/views/messages/index.blade.php
@extends('layouts.app')

@section('title')
    @include("partials.title-meta", ["title" => "SMS Messages" ])
@endsection

@section('topbar')
    @include('partials.topbar', ["title" => "Lonux","subtitle" => "Lists", "item" => "Messages",
    "activeitem" => "Message List"])
@endsection


@section('content')
    <div class="row">
        <div class="col-12 text-right">
            <a href="{{route('messages.create')}}" class="btn btn-primary mb-2">Create New Message</a>
        </div>
        
        @if (count($messages))
            @foreach ($messages ?? '' as $message)
                <div class="col-sm-6 col-xl-6">
                    <div class="card">
                        <div class="card-body">
                            <h4>{{$message->title}}</h4>
                            <p>{{$message->message}}</p>
                            
                            <a href="{{route('messages.edit', $message->id)}}" class="btn btn-info">Edit</a>
                            <form style="display: inline;" method="post" action="{{route('messages.destroy', $message->id)}}">
                                @csrf
                                @method('delete')
                                <button type="submit" class="btn btn-danger">Delete</button>
                            </form>
                        
                        </div>
                    </div>
                </div>
            @endforeach
        @else
            <div class="col-sm-6 col-xl-3">
                <div class="card">
                    <div class="card-body">
                        <div class="alert alert-info">No Messages to deisplay. <a href="{{route('messages.create')}}">create one</a>
                    </div>
                </div>
            </div>
        @endif

        @if (Session::has('done'))
            <div class="alert alert-info">{{session('done')}}</div>
        @endif
        
    </div>
    <!-- end row-->
@endsection

@section('scripts')
@endsection